# Generated by Django 5.1.15 on 2026-04-26 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('post_type', models.CharField(choices=[('wipe', 'Вайп'), ('update', 'Обновление'), ('event', 'Ивент'), ('sale', 'Акция'), ('other', 'Другое')], default='other', max_length=32, verbose_name='Тип')),
                ('excerpt', models.CharField(blank=True, max_length=255, verbose_name='Кратко')),
                ('body', models.TextField(verbose_name='Текст')),
                ('cover', models.ImageField(blank=True, upload_to='news/', verbose_name='Обложка')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опубликовано')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата публикации')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
    ]
