# Generated by Django 5.1.15 on 2026-04-27 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rebuild_legal_documents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legaldocument',
            name='body',
            field=models.TextField(blank=True, default='', editable=False, verbose_name='Технический дубль текста'),
        ),
        migrations.AlterField(
            model_name='legaldocument',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='legaldocument',
            name='text',
            field=models.TextField(blank=True, default='', verbose_name='Текст документа'),
        ),
        migrations.AlterField(
            model_name='legaldocument',
            name='title',
            field=models.CharField(help_text='Заголовок внутри страницы документа.', max_length=255, verbose_name='Заголовок'),
        ),
    ]
