# Generated by Django 5.1.15 on 2026-04-28 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_legaldocument_body_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HelpCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('subtitle', models.CharField(blank=True, max_length=255, verbose_name='Подпись')),
                ('icon', models.CharField(blank=True, help_text='Короткий текст или emoji. Например: ⚙, </>, $', max_length=32, verbose_name='Иконка')),
                ('sort_order', models.PositiveIntegerField(default=100, verbose_name='Сортировка')),
                ('is_public', models.BooleanField(default=True, verbose_name='Показывать')),
            ],
            options={
                'verbose_name': 'Категория помощи',
                'verbose_name_plural': 'Категории помощи',
                'ordering': ['sort_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='HelpItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Вопрос / заголовок')),
                ('body', models.TextField(verbose_name='Ответ / описание')),
                ('sort_order', models.PositiveIntegerField(default=100, verbose_name='Сортировка')),
                ('is_public', models.BooleanField(default=True, verbose_name='Показывать')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.helpcategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Пункт помощи',
                'verbose_name_plural': 'Пункты помощи',
                'ordering': ['category__sort_order', 'sort_order', 'title'],
            },
        ),
    ]
