# Generated by Django 5.1.15 on 2026-04-26 21:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SteamProfile',
            fields=[
                ('steam_id', models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='Steam ID64')),
                ('nickname', models.CharField(blank=True, max_length=255, verbose_name='Ник Steam')),
                ('profile_url', models.URLField(blank=True, verbose_name='Профиль Steam')),
                ('avatar_small', models.URLField(blank=True, verbose_name='Аватар маленький')),
                ('avatar_medium', models.URLField(blank=True, verbose_name='Аватар средний')),
                ('avatar_full', models.URLField(blank=True, verbose_name='Аватар полный')),
                ('real_name', models.CharField(blank=True, max_length=255, verbose_name='Реальное имя Steam')),
                ('country_code', models.CharField(blank=True, max_length=8, verbose_name='Страна')),
                ('persona_state', models.IntegerField(default=0, verbose_name='Steam статус')),
                ('first_seen_at', models.DateTimeField(auto_now_add=True, verbose_name='Первый вход')),
                ('last_seen_at', models.DateTimeField(blank=True, null=True, verbose_name='Последний вход')),
                ('last_known_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Последний IP')),
                ('last_user_agent', models.TextField(blank=True, verbose_name='Последний User-Agent')),
                ('is_project_staff', models.BooleanField(default=False, verbose_name='Сотрудник проекта')),
                ('is_banned_on_site', models.BooleanField(default=False, verbose_name='Бан на сайте')),
                ('ban_reason', models.TextField(blank=True, verbose_name='Причина бана')),
                ('notes', models.TextField(blank=True, verbose_name='Внутренние заметки')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='steam_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Steam профиль',
                'verbose_name_plural': 'Steam профили',
                'ordering': ['-last_seen_at', '-first_seen_at'],
            },
        ),
        migrations.CreateModel(
            name='SteamLoginEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('steam_id', models.CharField(blank=True, db_index=True, max_length=32, verbose_name='Steam ID64')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User-Agent')),
                ('success', models.BooleanField(default=False, verbose_name='Успешно')),
                ('reason', models.CharField(blank=True, max_length=255, verbose_name='Причина/статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='login_events', to='accounts.steamprofile')),
            ],
            options={
                'verbose_name': 'Вход Steam',
                'verbose_name_plural': 'История входов Steam',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlayerAdminNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('body', models.TextField(verbose_name='Текст')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_notes', to='accounts.steamprofile')),
            ],
            options={
                'verbose_name': 'Заметка по игроку',
                'verbose_name_plural': 'Заметки по игрокам',
                'ordering': ['-created_at'],
            },
        ),
    ]
