# Generated by Django 5.1.15 on 2026-04-27 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_role_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='steamloginevent',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP сайта'),
        ),
        migrations.AlterField(
            model_name='steamprofile',
            name='last_known_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='Последний IP сайта'),
        ),
    ]
