# Generated by Django 5.1.15 on 2026-04-27 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_steamloginevent_ip_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='steamprofile',
            name='last_seen_on_server_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Последний вход на Rust сервер'),
        ),
        migrations.AddField(
            model_name='steamprofile',
            name='last_server_ip',
            field=models.GenericIPAddressField(blank=True, db_index=True, null=True, verbose_name='Последний IP сервера Rust'),
        ),
        migrations.AlterField(
            model_name='steamprofile',
            name='last_seen_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Последний вход на сайт'),
        ),
    ]
