# Generated by Django 5.1.15 on 2026-04-28 14:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_steamprofile_last_seen_on_server_at_and_more'),
        ('shop', '0003_alter_product_options_alter_productcategory_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletTopUpRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_rub', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма пополнения, ₽')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('approved', 'Подтверждено'), ('rejected', 'Отклонено'), ('cancelled', 'Отменено')], db_index=True, default='pending', max_length=20, verbose_name='Статус')),
                ('comment', models.CharField(blank=True, max_length=255, verbose_name='Комментарий')),
                ('external_reference', models.CharField(blank=True, db_index=True, max_length=255, verbose_name='Внешний ID')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Обработано')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_wallet_topups', to=settings.AUTH_USER_MODEL)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_topup_requests', to='accounts.steamprofile', verbose_name='Профиль')),
            ],
            options={
                'verbose_name': 'Запрос пополнения',
                'verbose_name_plural': 'Запросы пополнений',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tx_type', models.CharField(choices=[('topup_request', 'Запрос пополнения'), ('topup_credit', 'Пополнение'), ('purchase', 'Покупка'), ('transfer_out', 'Перевод отправлен'), ('transfer_in', 'Перевод получен'), ('adjustment', 'Корректировка')], db_index=True, max_length=32, verbose_name='Тип операции')),
                ('amount_rub', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма операции, ₽')),
                ('balance_after_rub', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Баланс после операции, ₽')),
                ('reference_code', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='Код операции')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('counterparty_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallet_counterparty_transactions', to='accounts.steamprofile', verbose_name='Второй участник операции')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallet_transactions', to='shop.order', verbose_name='Заказ')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_transactions', to='accounts.steamprofile', verbose_name='Профиль')),
            ],
            options={
                'verbose_name': 'Операция кошелька',
                'verbose_name_plural': 'Операции кошелька',
                'ordering': ['-created_at'],
            },
        ),
    ]
