# Generated by Django 5.1.15 on 2026-04-28 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_wallettopuprequest_wallettransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='steamprofile',
            name='balance_rub',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Баланс, ₽'),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='amount_rub',
            field=models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Сумма операции, ₽'),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='balance_after_rub',
            field=models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Баланс после операции, ₽'),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='tx_type',
            field=models.CharField(choices=[('topup_credit', 'Пополнение'), ('purchase', 'Покупка'), ('purchase_refund', 'Возврат за покупку'), ('transfer_out', 'Перевод отправлен'), ('transfer_in', 'Перевод получен'), ('adjustment', 'Корректировка')], db_index=True, max_length=32, verbose_name='Тип операции'),
        ),
        migrations.DeleteModel(
            name='WalletTopUpRequest',
        ),
    ]
