# Generated by Django 5.1.15 on 2026-04-26 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RustServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('ip', models.CharField(blank=True, max_length=255, verbose_name='IP / домен')),
                ('port', models.PositiveIntegerField(default=28015, verbose_name='Порт')),
                ('connect_command', models.CharField(blank=True, max_length=255, verbose_name='Команда подключения')),
                ('server_type', models.CharField(default='Vanilla+', max_length=120, verbose_name='Тип')),
                ('rates', models.CharField(default='x2', max_length=64, verbose_name='Рейты')),
                ('map_size', models.PositiveIntegerField(default=4000, verbose_name='Размер карты')),
                ('max_players', models.PositiveIntegerField(default=200, verbose_name='Максимум игроков')),
                ('wipe_schedule', models.CharField(blank=True, max_length=255, verbose_name='Расписание вайпов')),
                ('battlemetrics_id', models.CharField(blank=True, max_length=64, verbose_name='BattleMetrics ID')),
                ('is_public', models.BooleanField(default=True, verbose_name='Показывать на сайте')),
                ('sort_order', models.PositiveIntegerField(default=100, verbose_name='Сортировка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Rust сервер',
                'verbose_name_plural': 'Rust серверы',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ServerSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('online_players', models.PositiveIntegerField(default=0, verbose_name='Онлайн')),
                ('queued_players', models.PositiveIntegerField(default=0, verbose_name='Очередь')),
                ('max_players', models.PositiveIntegerField(default=0, verbose_name='Макс игроков')),
                ('map_name', models.CharField(blank=True, max_length=255, verbose_name='Карта')),
                ('wipe_at', models.DateTimeField(blank=True, null=True, verbose_name='Последний/следующий вайп')),
                ('raw_payload', models.JSONField(blank=True, default=dict, verbose_name='Сырой ответ API')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='servers.rustserver')),
            ],
            options={
                'verbose_name': 'Снепшот сервера',
                'verbose_name_plural': 'Снепшоты серверов',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlayerServerStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kills', models.PositiveIntegerField(default=0, verbose_name='Убийства')),
                ('deaths', models.PositiveIntegerField(default=0, verbose_name='Смерти')),
                ('playtime_minutes', models.PositiveIntegerField(default=0, verbose_name='Минуты в игре')),
                ('last_seen_on_server', models.DateTimeField(blank=True, null=True, verbose_name='Последний раз на сервере')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='server_stats', to='accounts.steamprofile')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_stats', to='servers.rustserver')),
            ],
            options={
                'verbose_name': 'Статистика игрока',
                'verbose_name_plural': 'Статистика игроков',
                'unique_together': {('profile', 'server')},
            },
        ),
    ]
