# Generated by Django 5.1.15 on 2026-04-27 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_role_balance'),
        ('servers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rustserver',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='Показывать на сайте'),
        ),
        migrations.CreateModel(
            name='ServerPlayerConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_ip', models.GenericIPAddressField(db_index=True, verbose_name='IP на сервере')),
                ('nickname_at_moment', models.CharField(blank=True, max_length=255, verbose_name='Ник на момент входа')),
                ('first_seen_at', models.DateTimeField(blank=True, null=True, verbose_name='Первый вход с IP')),
                ('last_seen_at', models.DateTimeField(blank=True, null=True, verbose_name='Последний вход с IP')),
                ('connections_count', models.PositiveIntegerField(default=1, verbose_name='Кол-во входов')),
                ('raw_payload', models.JSONField(blank=True, default=dict, verbose_name='Сырой payload от сервера')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='server_connections', to='accounts.steamprofile')),
                ('server', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player_connections', to='servers.rustserver')),
            ],
            options={
                'verbose_name': 'Серверный вход игрока',
                'verbose_name_plural': 'Серверные входы игроков',
                'ordering': ['-last_seen_at', '-updated_at'],
                'indexes': [models.Index(fields=['server_ip'], name='servers_ser_server__918daf_idx'), models.Index(fields=['profile', 'server_ip'], name='servers_ser_profile_3985b0_idx')],
            },
        ),
    ]
