# Generated by Django 5.1.15 on 2026-04-27 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0002_alter_rustserver_is_public_serverplayerconnection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rustserver',
            name='battlemetrics_id',
        ),
        migrations.RemoveField(
            model_name='rustserver',
            name='connect_command',
        ),
        migrations.RemoveField(
            model_name='rustserver',
            name='wipe_schedule',
        ),
        migrations.AddField(
            model_name='rustserver',
            name='show_on_home',
            field=models.BooleanField(default=False, verbose_name='Показывать на главной'),
        ),
        migrations.AlterField(
            model_name='rustserver',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='Показывать на странице серверов'),
        ),
    ]
