# Generated by Django 5.1.15 on 2026-04-27 17:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0003_remove_rustserver_battlemetrics_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServerApiToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название API-ключа')),
                ('token', models.CharField(blank=True, max_length=128, unique=True, verbose_name='Токен')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('allowed_ip', models.GenericIPAddressField(blank=True, help_text='Можно оставить пустым на этапе разработки.', null=True, verbose_name='Разрешённый IP сервера')),
                ('last_used_at', models.DateTimeField(blank=True, null=True, verbose_name='Последнее использование')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_server_api_tokens', to=settings.AUTH_USER_MODEL)),
                ('server', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_tokens', to='servers.rustserver', verbose_name='Сервер')),
            ],
            options={
                'verbose_name': 'API-ключ сервера',
                'verbose_name_plural': 'API-ключи серверов',
                'ordering': ['-created_at'],
            },
        ),
    ]
