# Generated by Django 5.1.15 on 2026-04-28 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0004_serverapitoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServerShopCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Название')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('sort_order', models.PositiveIntegerField(default=100, verbose_name='Сортировка')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Внутренняя категория серверов',
                'verbose_name_plural': 'Внутренние категории серверов',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='rustserver',
            name='shop_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servers', to='servers.servershopcategory', verbose_name='Внутренняя категория магазина'),
        ),
    ]
