# Generated by Django 5.1.15 on 2026-04-26 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('product_type', models.CharField(choices=[('privilege', 'Привилегия'), ('kit', 'Кит'), ('cosmetic', 'Косметика'), ('service', 'Услуга'), ('other', 'Другое')], default='privilege', max_length=32, verbose_name='Тип')),
                ('short_description', models.CharField(blank=True, max_length=255, verbose_name='Короткое описание')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('price_rub', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена, ₽')),
                ('duration_days', models.PositiveIntegerField(default=30, verbose_name='Длительность, дней')),
                ('image', models.ImageField(blank=True, upload_to='shop/', verbose_name='Изображение')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('is_featured', models.BooleanField(default=False, verbose_name='На главной')),
                ('sort_order', models.PositiveIntegerField(default=100, verbose_name='Сортировка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('sort_order', models.PositiveIntegerField(default=100, verbose_name='Сортировка')),
            ],
            options={
                'verbose_name': 'Категория магазина',
                'verbose_name_plural': 'Категории магазина',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('pending', 'Ожидает оплаты'), ('paid', 'Оплачен'), ('granting', 'Выдается'), ('completed', 'Выполнен'), ('cancelled', 'Отменен'), ('refunded', 'Возврат')], default='draft', max_length=32, verbose_name='Статус')),
                ('total_rub', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Сумма, ₽')),
                ('customer_email', models.EmailField(blank=True, max_length=254, verbose_name='Email покупателя')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='accounts.steamprofile')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('yookassa', 'ЮKassa'), ('manual', 'Вручную')], default='yookassa', max_length=32, verbose_name='Провайдер')),
                ('provider_payment_id', models.CharField(blank=True, db_index=True, max_length=255, verbose_name='ID платежа у провайдера')),
                ('status', models.CharField(blank=True, max_length=64, verbose_name='Статус платежа')),
                ('amount_rub', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Сумма, ₽')),
                ('raw_payload', models.JSONField(blank=True, default=dict, verbose_name='Сырой payload')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='shop.order')),
            ],
            options={
                'verbose_name': 'Платежная транзакция',
                'verbose_name_plural': 'Платежные транзакции',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('price_rub', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена на момент покупки')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shop.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.product')),
            ],
            options={
                'verbose_name': 'Позиция заказа',
                'verbose_name_plural': 'Позиции заказов',
            },
        ),
        migrations.CreateModel(
            name='Entitlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Активно'), ('expired', 'Истекло'), ('revoked', 'Отозвано')], default='active', max_length=32, verbose_name='Статус')),
                ('starts_at', models.DateTimeField(verbose_name='Начало')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Окончание')),
                ('server_payload', models.JSONField(blank=True, default=dict, verbose_name='Данные для выдачи на сервер')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entitlements', to='accounts.steamprofile')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entitlements', to='shop.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.product')),
            ],
            options={
                'verbose_name': 'Выданное право/покупка',
                'verbose_name_plural': 'Выданные права/покупки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='shop.productcategory'),
        ),
    ]
