# Generated by Django 5.1.15 on 2026-04-27 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='old_price_rub',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Старая цена, ₽'),
        ),
        migrations.AddField(
            model_name='product',
            name='server_payload',
            field=models.JSONField(blank=True, default=dict, verbose_name='Данные для выдачи на сервер'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='category_type',
            field=models.CharField(choices=[('all', 'Все'), ('kits', 'Киты'), ('privileges', 'Привилегии'), ('resources', 'Ресурсы'), ('weapons', 'Оружие'), ('components', 'Компоненты'), ('cosmetics', 'Косметика'), ('services', 'Услуги'), ('other', 'Другое')], default='other', max_length=32, verbose_name='Тип категории'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='icon',
            field=models.CharField(blank=True, max_length=32, verbose_name='Иконка / emoji'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активна'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to='shop/products/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_rub',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Текущая цена, ₽'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('privilege', 'Привилегия'), ('kit', 'Кит'), ('resource', 'Ресурс'), ('weapon', 'Оружие'), ('component', 'Компонент'), ('cosmetic', 'Косметика'), ('service', 'Услуга'), ('other', 'Другое')], db_index=True, default='other', max_length=32, verbose_name='Тип'),
        ),
        migrations.CreateModel(
            name='ProductContentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название предмета')),
                ('amount', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('image', models.ImageField(blank=True, upload_to='shop/items/', verbose_name='Иконка предмета')),
                ('sort_order', models.PositiveIntegerField(default=100, verbose_name='Сортировка')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_items', to='shop.product')),
            ],
            options={
                'verbose_name': 'Состав товара',
                'verbose_name_plural': 'Состав товаров',
                'ordering': ['sort_order', 'name'],
            },
        ),
    ]
