# Generated by Django 5.1.15 on 2026-04-27 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_old_price_rub_product_server_payload_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name'], 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AlterModelOptions(
            name='productcategory',
            options={'ordering': ['name'], 'verbose_name': 'Категория магазина', 'verbose_name_plural': 'Категории магазина'},
        ),
        migrations.AlterModelOptions(
            name='productcontentitem',
            options={'ordering': ['name'], 'verbose_name': 'Состав кита', 'verbose_name_plural': 'Состав китов'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='server_payload',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sort_order',
        ),
        migrations.RemoveField(
            model_name='productcategory',
            name='category_type',
        ),
        migrations.RemoveField(
            model_name='productcategory',
            name='sort_order',
        ),
        migrations.RemoveField(
            model_name='productcontentitem',
            name='sort_order',
        ),
        migrations.AddField(
            model_name='product',
            name='detail_lines',
            field=models.TextField(blank=True, help_text='Каждый пункт с новой строки. Например: Доступ к /kit vip', verbose_name='Список возможностей / условий'),
        ),
        migrations.AddField(
            model_name='product',
            name='display_amount',
            field=models.CharField(blank=True, help_text='Для ресурса, оружия, компонента или косметики. Например: x1000, 1 шт., набор.', max_length=120, verbose_name='Количество / объём'),
        ),
        migrations.AddField(
            model_name='product',
            name='how_to_get',
            field=models.TextField(blank=True, help_text='Например: после покупки войди на сервер и используй команду /kit.', verbose_name='Как получить'),
        ),
        migrations.AddField(
            model_name='product',
            name='promo_duration_days',
            field=models.PositiveIntegerField(default=0, help_text='Если указать число больше 0, акция считается от даты создания товара.', verbose_name='Длительность акции, дней'),
        ),
        migrations.AlterField(
            model_name='entitlement',
            name='server_payload',
            field=models.JSONField(blank=True, default=dict, verbose_name='Данные для выдачи серверному агенту'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='shop.productcategory', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, help_text='Основное красивое описание товара. Можно писать обычным текстом.', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='product',
            name='duration_days',
            field=models.PositiveIntegerField(default=30, help_text='Для привилегий/услуг. Например, VIP на 30 дней.', verbose_name='Длительность действия, дней'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='Показывать на главной'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('privilege', 'Привилегия'), ('kit', 'Кит'), ('resource', 'Ресурс'), ('weapon', 'Оружие'), ('component', 'Компонент'), ('cosmetic', 'Косметика'), ('service', 'Услуга')], db_index=True, default='privilege', max_length=32, verbose_name='Тип товара'),
        ),
    ]
