# Generated by Django 5.1.15 on 2026-04-28 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0004_serverapitoken'),
        ('shop', '0003_alter_product_options_alter_productcategory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entitlement',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Выдано'),
        ),
        migrations.AddField(
            model_name='entitlement',
            name='delivery_error',
            field=models.TextField(blank=True, verbose_name='Ошибка выдачи'),
        ),
        migrations.AddField(
            model_name='entitlement',
            name='server',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entitlements', to='servers.rustserver', verbose_name='Сервер'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_error',
            field=models.TextField(blank=True, verbose_name='Ошибка выдачи'),
        ),
        migrations.AddField(
            model_name='order',
            name='selected_server',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='servers.rustserver', verbose_name='Сервер покупки'),
        ),
        migrations.AddField(
            model_name='product',
            name='server_scope',
            field=models.CharField(choices=[('all', 'Все серверы'), ('selected', 'Выбранные серверы')], default='all', max_length=16, verbose_name='Доступность по серверам'),
        ),
        migrations.AddField(
            model_name='product',
            name='servers',
            field=models.ManyToManyField(blank=True, related_name='products', to='servers.rustserver', verbose_name='Доступные серверы'),
        ),
        migrations.AlterField(
            model_name='entitlement',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает выдачи'), ('sent', 'Отправлено на сервер'), ('active', 'Активно'), ('failed', 'Ошибка выдачи'), ('refunded', 'Возвращено'), ('expired', 'Истекло'), ('revoked', 'Отозвано')], default='active', max_length=32, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('pending', 'Ожидает оплаты'), ('paid', 'Оплачен'), ('granting', 'Ожидает выдачи'), ('completed', 'Выполнен'), ('failed', 'Ошибка выдачи'), ('cancelled', 'Отменен'), ('refunded', 'Возврат')], default='draft', max_length=32, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_rub',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Сумма, ₽'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price_rub',
            field=models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Цена на момент покупки'),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='amount_rub',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Сумма, ₽'),
        ),
        migrations.AlterField(
            model_name='product',
            name='old_price_rub',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='Старая цена, ₽'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_rub',
            field=models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Текущая цена, ₽'),
        ),
    ]
