# Generated by Django 5.1.15 on 2026-04-28 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0005_servershopcategory_rustserver_shop_category'),
        ('shop', '0004_entitlement_delivered_at_entitlement_delivery_error_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='server_categories',
            field=models.ManyToManyField(blank=True, help_text='Товар будет доступен на серверах из выбранных внутренних категорий.', related_name='products', to='servers.servershopcategory', verbose_name='Внутренние категории серверов'),
        ),
    ]
