# Generated by Django 5.1.15 on 2026-04-26 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RuleSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('section_type', models.CharField(choices=[('server', 'Сервер'), ('discord', 'Discord'), ('shop', 'Магазин'), ('legal', 'Юридическое')], default='server', max_length=32, verbose_name='Тип')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('sort_order', models.PositiveIntegerField(default=100, verbose_name='Сортировка')),
                ('is_public', models.BooleanField(default=True, verbose_name='Показывать')),
            ],
            options={
                'verbose_name': 'Раздел правил',
                'verbose_name_plural': 'Разделы правил',
                'ordering': ['sort_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='RuleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=32, verbose_name='Номер/код')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('body', models.TextField(verbose_name='Текст правила')),
                ('punishment', models.CharField(blank=True, max_length=255, verbose_name='Наказание')),
                ('sort_order', models.PositiveIntegerField(default=100, verbose_name='Сортировка')),
                ('is_public', models.BooleanField(default=True, verbose_name='Показывать')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='rules.rulesection')),
            ],
            options={
                'verbose_name': 'Правило',
                'verbose_name_plural': 'Правила',
                'ordering': ['section__sort_order', 'sort_order', 'id'],
            },
        ),
    ]
