# Generated by Django 5.1.15 on 2026-04-28 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ruleitem',
            name='note',
            field=models.TextField(blank=True, verbose_name='Примечание'),
        ),
    ]
